swagger: "2.0"
info:
  description: "PPM Admin Adapter"
  version: "1.0.0"
  title: "PPM Admin Adapter"
tags:
- name: "admin"
  description: "Everything about admin adapter"
schemes:
- "https"
- "http"
paths:
  v1/admin/profiles:
    post:
      tags:
      - "admin"
      summary: "check deleted profiles"
      description: "check deleted"
      operationId: "checkDeletedProfiles"
      consumes:
      - "text/plain"
      produces:
      - "text/plain"
      parameters:
      - in: "body"
        name: "patientIds"
        required: true
        description: "list id of patient profiles"
        schema:
          type: "array"
          items:
            type: "string"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              type: "string"
        400:
          description: "Invalid input"
        500:
          description: "Internal server error"